version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aamenn-frontend
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - aamenn-network
    restart: unless-stopped

networks:
  aamenn-network:
    external: true
    name: aamenn-backend_default
